
package dashboard;

import clases.Cliente;
import conexionBD.ClienteDAO;
import java.awt.Color;
import javax.swing.JOptionPane;
import login.Validacion;


/**
 * Panel para la modificación de datos de un cliente en el sistema.
 * Permite cambiar el nombre de usuario, correo electrónico, contraseña y DNI.
 * Utiliza validaciones para asegurar la correcta entrada de datos.
 * Selecciona un cliente existente para modificar sus datos.
 */
public class EditarDatosCliente extends javax.swing.JPanel {

    // Instancia de la clase de validación
    Validacion validacion = new Validacion();
    
    // Cliente a ser modificado
    Cliente cliente = new Cliente();
    
    /**
     * Constructor que inicializa los componentes del panel.
     */
    public EditarDatosCliente() {
        initComponents();
    }
    
    /**
     * Establece el cliente que se va a modificar.
     *
     * @param cliente Cliente a ser modificado.
     */
    public void setCliente(Cliente cliente){
        this.cliente = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        tittel = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        correoTxt = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        btnChange = new javax.swing.JButton();
        dniTxt = new javax.swing.JTextField();
        lblDni = new javax.swing.JLabel();
        passTxt = new javax.swing.JPasswordField();

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittel.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        tittel.setText("MODIFICAR DATOS");
        panelMain.add(tittel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 410, -1));

        userTxt.setForeground(new java.awt.Color(153, 153, 153));
        userTxt.setText("Ingrese su usuario");
        userTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTxtMousePressed(evt);
            }
        });
        panelMain.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 190, -1));

        correoTxt.setForeground(new java.awt.Color(153, 153, 153));
        correoTxt.setText("Ingrese su correo");
        correoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                correoTxtMousePressed(evt);
            }
        });
        panelMain.add(correoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 190, -1));

        lblPass.setText("Contraseña");
        panelMain.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        lblUser.setText("Usuario: ");
        panelMain.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        lblCorreo.setText("Correo");
        panelMain.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        btnChange.setText("CAMBIAR");
        btnChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangeMouseClicked(evt);
            }
        });
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        panelMain.add(btnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        dniTxt.setForeground(new java.awt.Color(153, 153, 153));
        dniTxt.setText("Ingrese su dni");
        dniTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dniTxtMousePressed(evt);
            }
        });
        panelMain.add(dniTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 190, -1));

        lblDni.setText("Dni");
        panelMain.add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        passTxt.setText("********");
        passTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTxtMousePressed(evt);
            }
        });
        panelMain.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangeActionPerformed

    /**
     * Cambia el texto "Ingrese correo" al hacer click para ingresar correo.
     * @param evt El evento del mouse.
    */
    private void correoTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correoTxtMousePressed
        if (correoTxt.getText().equals("Ingrese su correo")) {
            correoTxt.setText("");
            correoTxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_correoTxtMousePressed

    /**
     * Cambia el texto "Ingrese su usuario" al hacer click para ingresar el usuario.
     * @param evt El evento del mouse.
    */
    private void userTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMousePressed
        if (userTxt.getText().equals("Ingrese su usuario")) {
            userTxt.setText("");
            userTxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_userTxtMousePressed

    /**
     * Realiza el cambio de datos cuando se hace clic en el botón "CAMBIAR".
     *
     * @param evt El evento del mouse.
     */
    private void btnChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeMouseClicked
        
        String usuario = userTxt.getText();
        String correo = correoTxt.getText();
        String contraseña = new String(passTxt.getPassword()); 
        String dni = dniTxt.getText();
        
        // Llama al método de validación
        if (!validacion.validarRegistro(usuario, correo, contraseña, dni)) {
            return; // Detiene la ejecución si la validación no es exitosa
        }
        
        ClienteDAO clienteDAO = new ClienteDAO();
        
        int id = cliente.getId();
        Object[] o = new Object[5];
        
        try {
           
            o[0] = usuario;
            o[1] = correo;
            o[2] = contraseña;
            o[3] = Integer.parseInt(dni);
            o[4] = id;

            clienteDAO.actualizar(o);
            
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null, "Error: " + ex.toString());
        }
    }//GEN-LAST:event_btnChangeMouseClicked

    /**
     * Cambia el texto "Ingrese su dni" al hacer click para ingresar el dni.
     * @param evt El evento del mouse.
    */
    private void dniTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dniTxtMousePressed
        if (dniTxt.getText().equals("Ingrese su dni")) {
            dniTxt.setText("");
            dniTxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_dniTxtMousePressed

    /**
     * Cambia el texto "********" al hacer click para ingresar contraseña.
     * @param evt El evento del mouse.
    */
    private void passTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMousePressed
        if (String.valueOf(passTxt.getPassword()).equals("********")) {
            passTxt.setText("");
            passTxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_passTxtMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JTextField dniTxt;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JLabel tittel;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
