/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dashboard;

/**
 *
 * @author david
 */
public class OptionsClient extends javax.swing.JPanel {

    
    /**
     * Creates new form OptionsClient
     */
    public OptionsClient() {
        initComponents();
    }

    
    public void colocarDatos(String usuario, String correo, int dni ){
        txtUsuario.setText(usuario);
        txtCorreo.setText(correo);
        txtDni.setText(Integer.toString(dni));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatosPersonales = new javax.swing.JPanel();
        lblDatosPersonales = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        txtDni = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        PanelEstadoDeCuenta = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tittleInformacionPersonal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(204, 204, 0));
        setPreferredSize(new java.awt.Dimension(660, 440));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDatosPersonales.setBackground(new java.awt.Color(255, 255, 255));
        panelDatosPersonales.setForeground(new java.awt.Color(204, 204, 204));
        panelDatosPersonales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDatosPersonales.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        lblDatosPersonales.setForeground(new java.awt.Color(204, 0, 204));
        lblDatosPersonales.setText("DATOS PERSONALES");
        panelDatosPersonales.add(lblDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 18, -1, -1));

        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        panelDatosPersonales.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, 20));
        panelDatosPersonales.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 130, 20));
        panelDatosPersonales.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 20));

        lblDni.setForeground(new java.awt.Color(153, 0, 153));
        lblDni.setText("Dni:");
        panelDatosPersonales.add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        lblUsuario.setForeground(new java.awt.Color(153, 0, 153));
        lblUsuario.setText("Usuario:");
        panelDatosPersonales.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lblCorreo.setForeground(new java.awt.Color(153, 0, 153));
        lblCorreo.setText("Correo:");
        panelDatosPersonales.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        add(panelDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 540, 170));

        PanelEstadoDeCuenta.setBackground(new java.awt.Color(255, 255, 255));
        PanelEstadoDeCuenta.setForeground(new java.awt.Color(204, 204, 204));
        PanelEstadoDeCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("ESTADO DE LA CUENTA");
        PanelEstadoDeCuenta.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        add(PanelEstadoDeCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 540, 120));

        tittleInformacionPersonal.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        tittleInformacionPersonal.setForeground(new java.awt.Color(204, 0, 204));
        tittleInformacionPersonal.setText("MI INFORMACION PERSONAL");
        add(tittleInformacionPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 310, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        
    }//GEN-LAST:event_txtUsuarioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEstadoDeCuenta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDatosPersonales;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelDatosPersonales;
    private javax.swing.JLabel tittleInformacionPersonal;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtDni;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
