/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.panels;

import clases.PC;
import clases.Producto;
import clases.command.Constantes;
import conexionBD.ProductoDAO;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author henry
 */
public class AgregarPc extends javax.swing.JPanel {

    /**
     * Creates new form AgregarPc
     */
    PC pc;
    ProductoDAO productoDAO = new ProductoDAO();
    public AgregarPc() {
        
        initComponents();
        cargarComboBox();
    }
    
    private void cargarComboBox(){
        
        List<Producto> listaMother =  productoDAO.obtenerProductosPorTipo("motherboard");
        for(Producto a : listaMother){
            cBoMoBo.addItem(a.getTipo()+"marca "+a.getMarca());
        }
        List<Producto> listaRam =  productoDAO.obtenerProductosPorTipo("memoria ram");
        for(Producto a : listaRam){
            cBoxMemRam.addItem(a.getTipo()+" marca "+a.getMarca());
        }
        List<Producto> listaRom =  productoDAO.obtenerProductosPorTipo("memoria rom");
        for(Producto a : listaRom){
            cBoxMemRom.addItem(a.getTipo()+" marca "+a.getMarca());
        }
        List<Producto> listaMoBo =  productoDAO.obtenerProductosPorTipo("motherboard");
        for(Producto a : listaMoBo){
            cBoMoBo.addItem(a.getTipo()+" marca "+a.getMarca());
        }
        List<Producto> listaPro =  productoDAO.obtenerProductosPorTipo("procesador");
        for(Producto a : listaPro){
            cBoxProce.addItem(a.getTipo()+" marca "+a.getMarca());
        }
        List<Producto> listaRefr =  productoDAO.obtenerProductosPorTipo("refrigeracion");
        for(Producto a : listaRefr){
            cBoxRefrig.addItem(a.getTipo()+" marca "+a.getMarca());
        }
        cBoxRefrig.addItem("sin seleccionar");
        
        List<Producto> listaMouse =  productoDAO.obtenerProductosPorTipo("mouse");
        cBoxMouse.addItem("sin seleccionar");
        for(Producto a : listaMouse){
            cBoxMouse.addItem(a.getTipo()+" marca "+a.getMarca());
        }
        
        
        List<Producto> listaTar =  productoDAO.obtenerProductosPorTipo("tarjeta grafica");
        cBoxTarjGraf.addItem("sin seleccionar");
        for(Producto a : listaTar){
            cBoxTarjGraf.addItem(a.getTipo()+" marca "+a.getMarca());
        }
        
        
        List<Producto> listaAud =  productoDAO.obtenerProductosPorTipo("audifonos");
        cBoxAudif.addItem("sin seleccionar");
        for(Producto a : listaAud){
            cBoxAudif.addItem(a.getTipo()+" marca "+a.getMarca());
        }
        
        List<Producto> listaTec =  productoDAO.obtenerProductosPorTipo("teclado");
        cBoxTeclado.addItem("sin seleccionar");
        for(Producto a : listaTec){
            cBoxTeclado.addItem(a.getTipo()+" marca "+a.getMarca());
        }
        
        List<Producto> listaMon =  productoDAO.obtenerProductosPorTipo("monitor");
        cBoxMonitor.addItem("sin seleccionar");
        for(Producto a : listaMon){
            cBoxMonitor.addItem(a.getTipo()+" marca "+a.getMarca());
        }
        
    }
    
    private Producto agregarCom(String prod, JComboBox box){
        List<Producto> valoresEspecificos = productoDAO.obtenerProductosPorTipo(prod);
            int selectedIndex = box.getSelectedIndex();
            
            if (selectedIndex >= 0 && selectedIndex < valoresEspecificos.size()) {
               if(valoresEspecificos.get(selectedIndex).getStock()!=0){
                    String valorEspecifico = valoresEspecificos.get(selectedIndex).getTipo();
                return valoresEspecificos.get(selectedIndex);
                }else{
                    return null;
                }
            }else{
                return null;
            }
        
    }
    
    private Producto agregarPer(String prod, JComboBox box){
        List<Producto> valoresEspecificos = productoDAO.obtenerProductosPorTipo(prod);
            int selectedIndex = box.getSelectedIndex()-1;
            if (selectedIndex >= 0 && selectedIndex < valoresEspecificos.size()) {
                if(valoresEspecificos.get(selectedIndex).getStock()!=0){
                    String valorEspecifico = valoresEspecificos.get(selectedIndex).getTipo();
                return valoresEspecificos.get(selectedIndex);
                }else{
                    return null;
                }
                
            }else{
                return null;
            }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cBoxMemRam = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cBoxMemRom = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cBoxProce = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cBoMoBo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cBoxRefrig = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cBoxTarjGraf = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cBoxMouse = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cBoxAudif = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cBoxTeclado = new javax.swing.JComboBox<>();
        cBoxMonitor = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Memoria RAM");

        jLabel2.setText("Memoria ROM");

        jLabel3.setText("Procesador");

        jLabel4.setText("MotherBoard");

        cBoMoBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoMoBoActionPerformed(evt);
            }
        });

        jLabel5.setText("Refrigeración");

        jLabel6.setText("Tarjeta Grafica");

        jLabel7.setText("Mouse");

        jLabel8.setText("Audifonos");

        jLabel9.setText("Teclado");

        jLabel10.setText("Monitor");

        jButton1.setText("Nueva Pc");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cBoxTarjGraf, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cBoxRefrig, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cBoMoBo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addComponent(cBoxProce, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cBoxMemRom, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cBoxMemRam, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cBoxMouse, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cBoxAudif, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cBoxTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(cBoxMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxMemRam, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cBoxMouse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxMemRom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cBoxAudif, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxProce, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cBoxTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoMoBo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cBoxMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxRefrig, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxTarjGraf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(agregarCom("memoria ram", cBoxMemRam)== null || agregarCom("memoria rom", cBoxMemRom)== null || agregarCom("procesador", cBoxProce)==null || agregarCom("motherboard", cBoMoBo)==null){
            JOptionPane.showMessageDialog(this, "El stock esta en 0");
        }else{
                List<Producto> prod = new ArrayList<Producto>();
            prod.add(agregarCom("memoria ram", cBoxMemRam));
            prod.add(agregarCom("memoria rom", cBoxMemRom));
            prod.add(agregarCom("procesador", cBoxProce));
            prod.add(agregarCom("motherboard", cBoMoBo));
            if(agregarPer("refrigeracion", cBoxTarjGraf)!=null){
                prod.add(agregarPer("refrigeracion", cBoxTarjGraf));
            }
            if(agregarPer("mouse", cBoxMouse)!=null){
                prod.add(agregarPer("mouse", cBoxMouse));
            }
            if(agregarPer("audifonos", cBoxAudif)!=null){
                prod.add(agregarPer("audifonos", cBoxAudif));
            }
            if(agregarPer("teclado", cBoxTeclado)!=null){
                prod.add(agregarPer("teclado", cBoxTeclado));
            }
            if(agregarPer("monitor", cBoxMonitor)!=null){
                prod.add(agregarPer("monitor", cBoxMonitor));
            }
            
            
            
            for(Producto a: prod){
                System.out.println(a.getModelo());
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cBoMoBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoMoBoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoMoBoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cBoMoBo;
    public javax.swing.JComboBox<String> cBoxAudif;
    public javax.swing.JComboBox<String> cBoxMemRam;
    public javax.swing.JComboBox<String> cBoxMemRom;
    public javax.swing.JComboBox<String> cBoxMonitor;
    public javax.swing.JComboBox<String> cBoxMouse;
    public javax.swing.JComboBox<String> cBoxProce;
    public javax.swing.JComboBox<String> cBoxRefrig;
    public javax.swing.JComboBox<String> cBoxTarjGraf;
    public javax.swing.JComboBox<String> cBoxTeclado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
